name: test
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: Run tests
      env:
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      run: deno task test